source 'http://git.babybus.co/Babybus-iOS/Specs/babybus-specs.git'

target 'SVG' do
  use_frameworks!

  pod 'SDWebImageSVGCoder'
  pod 'SDWebImageSVGKitPlugin'
  pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '3.x'
end

